[package]
name = "rynna-workflows"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
[dependencies]
rynna-core = { path = "../rynna-core" }
async-trait.workspace = true
serde_json.workspace = true
fs2.workspace = true
tempfile.workspace = true
uuid.workspace = true
rynna-config = { path = "../rynna-config" }
tokio.workspace = true

[dev-dependencies]
